// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toyjxqogwsoqmxhedpgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRveWp4cW9nd3NvcW14aGVkcGdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTcyOTAsImV4cCI6MjA2NTk5MzI5MH0.V8-P1U41arKC2lxA7Sw4rkaZn192VLu8AGGsrEVZLbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);